default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: pokedex_development

production:
  <<: *default
  database: pokedex_production
  username: pokedex
  password: <%= ENV['POKEDEX_DATABASE_PASSWORD'] %>
